config/routes.rb
Rails.application.routes.draw do
  namespace :api  do
    resources :rs, format: :json
  end

  resources :causes

  resources :fuels
  resources :stations

end

app/models/cause.rb
class Cause < ActiveRecord::Base
end

app/models/fuel.rb
class Fuel < ActiveRecord::Base
    has_and_belongs_to_many :stations
end

app/models/immobilization.rb
class Immobilization < ActiveRecord::Base
  belongs_to :verification
end

app/models/municipality.rb
class Municipality < ActiveRecord::Base
	belongs_to :state
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :station;
  
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :stations
  has_many :municipalities
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :state
  has_many :verification
  belongs_to :organization
 has_and_belongs_to_many :fuels
   accepts_nested_attributes_for :state,:verification, :organization #, :fuels
end 

app/models/verification.rb
class Verification < ActiveRecord::Base
  belongs_to :station
  has_many :immobilization
end

app/controllers/api/rs_controller.rb
class Api::RsController < ApplicationController
	respond_to :json
	#PER_PAGES__RECORD =9
	def index
		#municipalities_paginated = Municipality.order('id').page(params[:page]).per(PER_PAGES__RECORD)
		@municipios= Municipality.where(state: params[:state])  if params[:state].present?
		
		respond_with @municipios
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  before_action :set_cause, only: [:show, :edit, :update, :destroy]

  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
  end

  # GET /causes/new
  def new
    @cause = Cause.new
  end

  # GET /causes/1/edit
  def edit
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(cause_params)

    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render :show, status: :created, location: @cause }
      else
        format.html { render :new }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /causes/1
  # PATCH/PUT /causes/1.json
  def update
    respond_to do |format|
      if @cause.update(cause_params)
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { render :show, status: :ok, location: @cause }
      else
        format.html { render :edit }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause.destroy
    respond_to do |format|
      format.html { redirect_to causes_url, notice: 'Cause was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cause
      @cause = Cause.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cause_params
      params.require(:cause).permit(:clave, :descrition, :cause, :technique_description)
    end
end

app/controllers/fuels_controller.rb
class FuelsController < ApplicationController
  before_action :set_fuel, only: [:show, :edit, :update, :destroy]

  # GET /fuels
  # GET /fuels.json
  def index
    @fuels = Fuel.all
  end

  # GET /fuels/1
  # GET /fuels/1.json
  def show
  end

  # GET /fuels/new
  def new
    @fuel = Fuel.new
  end

  # GET /fuels/1/edit
  def edit
  end

  # POST /fuels
  # POST /fuels.json
  def create
    @fuel = Fuel.new(fuel_params)

    respond_to do |format|
      if @fuel.save
        format.html { redirect_to @fuel, notice: 'Fuel was successfully created.' }
        format.json { render :show, status: :created, location: @fuel }
      else
        format.html { render :new }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuels/1
  # PATCH/PUT /fuels/1.json
  def update
    respond_to do |format|
      if @fuel.update(fuel_params)
        format.html { redirect_to @fuel, notice: 'Fuel was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuel }
      else
        format.html { render :edit }
        format.json { render json: @fuel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuels/1
  # DELETE /fuels/1.json
  def destroy
    @fuel.destroy
    respond_to do |format|
      format.html { redirect_to fuels_url, notice: 'Fuel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel
      @fuel = Fuel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fuel_params
      params.require(:fuel).permit(:name, :descrition)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def new
    
  end
  def create
  #	 render plain: params[:fuelid].inspect
	params.permit!
 	@station = Station.new(params[:station])

 if	@station.save
  fuels = Fuel.find params[:fuel_id]
  @station.fuels=fuels
 	redirect_to @station
 else
  render :new
 end
end
def show
  		@station = Station.find(params[:id])
end

def index
  @stations = Station.all
end
def edit  
  @station = Station.find(params[:id])
#render plain: params[:id].inspect
end
def update
  @station = Station.find(params[:id])
 
  if @station.update(station_params)
    redirect_to @station
  else
    render 'edit'
  end
end

private
  def station_params
    params.require(:station).permit(:station_number, :social_reason,:address , :zip_code ,:state_id, :municipality_id, :siic, :colony, :phone, :email, :vpm, :cualli, :latitude, :longitude, :organization_id )
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/fuels_helper.rb
module FuelsHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/causes/_form.html.erb
<%= form_for(@cause) do |f| %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :clave %><br>
    <%= f.text_field :clave %>
  </div>
  <div class="field">
    <%= f.label :descrition %><br>
    <%= f.text_area :descrition %>
  </div>
  <div class="field">
    <%= f.label :cause %><br>
    <%= f.text_field :cause %>
  </div>
  <div class="field">
    <%= f.label :technique_description %><br>
    <%= f.text_area :technique_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<h1>Editing cause</h1>

<%= render 'form' %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

app/views/causes/index.html.erb
<h1>Listing causes</h1>

<table>
  <thead>
    <tr>
      <th>Clave</th>
      <th>Descrition</th>
      <th>Cause</th>
      <th>Technique description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @causes.each do |cause| %>
      <tr>
        <td><%= cause.clave %></td>
        <td><%= cause.descrition %></td>
        <td><%= cause.cause %></td>
        <td><%= cause.technique_description %></td>
        <td><%= link_to 'Show', cause %></td>
        <td><%= link_to 'Edit', edit_cause_path(cause) %></td>
        <td><%= link_to 'Destroy', cause, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cause', new_cause_path %>

app/views/causes/new.html.erb
<h1>New cause</h1>

<%= render 'form' %>

<%= link_to 'Back', causes_path %>

app/views/causes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clave:</strong>
  <%= @cause.clave %>
</p>

<p>
  <strong>Descrition:</strong>
  <%= @cause.descrition %>
</p>

<p>
  <strong>Cause:</strong>
  <%= @cause.cause %>
</p>

<p>
  <strong>Technique description:</strong>
  <%= @cause.technique_description %>
</p>

<%= link_to 'Edit', edit_cause_path(@cause) %> |
<%= link_to 'Back', causes_path %>

app/views/fuels/_form.html.erb
<%= form_for(@fuel) do |f| %>
  <% if @fuel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuel.errors.count, "error") %> prohibited this fuel from being saved:</h2>

      <ul>
      <% @fuel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descrition %><br>
    <%= f.text_area :descrition %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fuels/edit.html.erb
<h1>Editing fuel</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuel %> |
<%= link_to 'Back', fuels_path %>

app/views/fuels/index.html.erb
<h1>Listing fuels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descrition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuels.each do |fuel| %>
      <tr>
        <td><%= fuel.name %></td>
        <td><%= fuel.descrition %></td>
        <td><%= link_to 'Show', fuel %></td>
        <td><%= link_to 'Edit', edit_fuel_path(fuel) %></td>
        <td><%= link_to 'Destroy', fuel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel', new_fuel_path %>

app/views/fuels/new.html.erb
<h1>New fuel</h1>

<%= render 'form' %>

<%= link_to 'Back', fuels_path %>

app/views/fuels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fuel.name %>
</p>

<p>
  <strong>Descrition:</strong>
  <%= @fuel.descrition %>
</p>

<%= link_to 'Edit', edit_fuel_path(@fuel) %> |
<%= link_to 'Back', fuels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admfullgas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= csrf_meta_tags %>
  <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta http-equiv="Pragma" content="no-cache" />
<meta http-equiv="Expires" content="0" />
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stations/edit.html.erb
<h1>Editar estación</h1>
<%= form_for :station, url: station_path(@station), method: :patch do |f| %>
 <p>
     <%= f.label :station_number %><br>
    <%= f.text_field :station_number %>
  </p>
  <p>
     <%= f.label :social_reason %><br>
    <%= f.text_field :social_reason %>
  </p>
   <p>
     <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
     <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </p>
   <p>
     <%= f.label :state_id %><br>
     <%= collection_select(:station, :state_id, State.all, :id, :name) %>
  </p>
   <p>
     <%= f.label :municipality_id %><br>
    <%= collection_select(:station, :municipality_id, Municipality.where(state: 1) , :id, :name)%>
  </p>
  <p>
     <%= f.label :siic %><br>
    <%= f.text_field :siic %>
  </p>
   <p>
     <%= f.label :colony %><br>
    <%= f.text_field :colony %>
  </p>
     <p>
     <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
    <p>
     <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
    <p>
     <%= f.label :vpm %><br>
    <%= f.text_field :vpm %>
  </p>
    <p>
     <%= f.label :cualli %>
    <%= check_box_tag 'station_cualli',true  %>
  </p>
  <div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
    <p>
     <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </p>
    <p>
     <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </p>
    <p>
     <%= f.label :organization_id %><br>
    <%= collection_select(:station, :organization_id, Organization.all, :id, :name) %>
  </p>
   <p>
     <%= f.label :fuel_id %><br>
  <%= select_tag :fuel_id, options_from_collection_for_select(Fuel.all, 'id', 'name'), :multiple => true %>
   <p>
   
 <p>
    <%= f.submit %><%= link_to 'Regresar', stations_path %>
  </p>
<% end %>

app/views/stations/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
      <th colspan="2"></th>
  </tr>
 
  <% @stations.each do |station| %>
    <tr>
      <td><%= station.station_number %></td>
      <td><%= station.social_reason %></td>
      <td><%= link_to 'Mostrar', station_path(station) %></td>
          <td><%= link_to 'Modificar', edit_station_path(station.id) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Agregar estación', new_station_path %>

app/views/stations/new.html.erb
<h1>Agregar estación</h1>
<%= form_for :station, url: stations_path do |f| %>
 <p>
     <%= f.label :station_number %><br>
    <%= f.text_field :station_number %>
  </p>
  <p>
     <%= f.label :social_reason %><br>
    <%= f.text_field :social_reason %>
  </p>
   <p>
     <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
     <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </p>
   <p>
     <%= f.label :state_id %><br>
     <%= collection_select(:station, :state_id, State.all, :id, :name) %>
  </p>
   <p>
     <%= f.label :municipality_id %><br>
    <%= collection_select(:station, :municipality_id, Municipality.where(state: 1) , :id, :name)%>
  </p>
  <p>
     <%= f.label :siic %><br>
    <%= f.text_field :siic %>
  </p>
   <p>
     <%= f.label :colony %><br>
    <%= f.text_field :colony %>
  </p>
     <p>
     <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
    <p>
     <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
    <p>
     <%= f.label :vpm %><br>
    <%= f.text_field :vpm %>
  </p>
    <p>
     <%= f.label :cualli %>
    <%= check_box_tag 'station_cualli',true  %>
  </p>
  <div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
    <p>
     <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </p>
    <p>
     <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </p>
    <p>
     <%= f.label :organization_id %><br>
    <%= collection_select(:station, :organization_id, Organization.all, :id, :name) %>
  </p>
   <p>
     <%= f.label :fuel_id %><br>
  <%= select_tag :fuel_id, options_from_collection_for_select(Fuel.all, 'id', 'name'), :multiple => true %>
   <p>
   
 <p>
    <%= f.submit %><%= link_to 'Regresar', stations_path %>
  </p>
<% end %>

app/views/stations/show.html.erb
 <p>      <strong>Numero de estación:</strong><br>     
 <%= @station.station_number %>   </p>  
  <p>       <strong>Tazon social:</strong><br>     
  <%= @station.social_reason %>   </p>
<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>